// Generated by dts-bundle-generator v6.12.0

declare const domains: readonly [
	"kanji",
	"words"
];
export declare type Domain = typeof domains[number];
export declare type Row = [
	id: number,
	character: string,
	jlpt: number,
	meaning1: string,
	meaning2OrHiragana: string
];
export declare type JlptWordEntry = [
	word: string,
	hiragana: "" | string,
	english: string
];
/** KANJIS */
export declare const Kanjis: Row[];
/** WORDS */
export declare const jlpts: JlptWordEntry[][];
export declare const Words: Row[];
/** FUNCTIONS */
export declare function getRowFromId(domain: Domain, id: number): Row;
export declare function wordExists(word: string): boolean;
export declare function getExactSearch(word: string): Row | null;
export declare type SentenceMeta = {
	word: string;
	meta: Row | null;
}[];
export declare function parseSentence(sentence: string): SentenceMeta;

export {};
